# Generated by Django 6.0 on 2025-12-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_me_en',
            field=models.TextField(default='I am a web developer specializing in Django and React.', verbose_name='About Me English'),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_me_fa',
            field=models.TextField(default='من توسعه\u200cدهنده وب هستم و در Django و React تخصص دارم.', verbose_name='درباره من فارسی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name_en',
            field=models.CharField(default='Ali Rezaei', max_length=100, verbose_name='Full Name English'),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name_fa',
            field=models.CharField(default='علی رضایی', max_length=100, verbose_name='نام کامل فارسی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='hello@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, default='https://github.com/username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.CharField(default='Full-Stack Developer', max_length=150, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, default='https://www.linkedin.com/in/username/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='+98 912 345 6789', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, default='https://example.com'),
        ),
    ]
